### ISSUE TITLE
Can't create mixing bowl in begin of the game

### ISSUE THREAD

**Issue by kosc** [Mechaenetia/mechaenetia#11]
Hello!

Trying to create mixing bowl to get bronze.
To create mixing bowl I need robot arm chisel tip, chisel, or pocket multitool (chisel).
But to create simplest tool (I presume it's chisel), I need Steel Chisel head, with I can't get on this step of the game.

**Comment by GregoriusT** [comment]
wrong issue tracker by the way. also you already told me in chat, and that is way more than enough to let me know about an issue. ;)

**Comment by jusvit** [comment]
😔

**Comment by GregoriusT** [comment]
The issue is fixed in GT6 Indev by the way. Should be released whenever I release it.

And yes I somehow got back stuck at GT6 instead of working on Mechaenetia. I blame the "where the heck do I even start" syndrome, the easy availability of working on GT6, and brand new 1.7.10 Mods appearing out of nowhere to add Compatibility for GT6 to.
